agents:

  ChatAgent:
    model: "deepseek/deepseek-chat"
    api_key: "sk-2d377ffeddf240dea637617fbd688c27"
    url: "https://api.deepseek.com"
    model_config_dict:  # Additional model configuration
      temperature: 0.7

